language: python
python:
  - "3.4"

# each line defined in env will create a new parallel test job on Travis
env:
  - TARGETS="lint test-unit"
  - TARGETS="test-functional test-unit-via-clusterrunner"

install:
  - make init

script:
  - export PYTHONPATH=.:$PYTHONPATH  # this is needed to get our custom pylint plugin to load correctly on Travis
  - export CR_VERBOSE=1  # turns on stdout logging for master and slave services during functional tests
  - make $TARGETS
